// Reviewed claims for the pinned public release. Each text field is read from
// real upstream bytes by extract.mjs; these descriptions are source analysis.
const src = 'packages/opencode/src/';
const llm = 'packages/llm/src/';
const core = 'packages/core/src/';
export const toolFiles = [
  ['apply_patch', 'apply_patch', 'Model API ID includes gpt-, excludes oss and gpt-4; registry chooses apply_patch instead of edit/write.'],
  ['edit', 'edit', 'Registry model selection does not choose apply_patch; final permission and user.tools filtering still apply.'],
  ['glob', 'glob', 'Built-in registry tool; final permission and user.tools filtering apply.'],
  ['grep', 'grep', 'Built-in registry tool; final permission and user.tools filtering apply.'],
  ['lsp', 'lsp', 'Registered only with experimentalLspTool enabled; final permission and user.tools filtering apply.'],
  ['plan-enter', null, 'Shipped description file, with no import or registry implementation found in pinned packages source; do not assume it is advertised.'],
  ['plan-exit', 'plan', 'Registered only with experimentalPlanMode enabled and client equal to cli; final permission and user.tools filtering apply.'],
  ['question', 'question', 'Registered when client is app, cli or desktop, or enableQuestionTool is set; final permission and user.tools filtering apply.'],
  ['read', 'read', 'Built-in registry tool; nearby instruction files may be returned with real file contents; final permission and user.tools filtering apply.'],
  ['skill', 'skill', 'Built-in registry tool; executing it loads a real available skill; final permission and user.tools filtering apply.'],
  ['task', 'task', 'Registry appends permitted subagent descriptions. experimentalBackgroundSubagents adds background guidance and changes the advertised parameter schema.'],
  ['todowrite', 'todo', 'Built-in registry tool; final permission and user.tools filtering apply.'],
  ['webfetch', 'webfetch', 'Built-in registry tool; final permission and user.tools filtering apply.'],
  ['websearch', 'websearch', 'Advertised for opencode/opencode-go providers or enabled Exa/Parallel flags; {{year}} is replaced at tool initialization.'],
  ['write', 'write', 'Registry model selection does not choose apply_patch; final permission and user.tools filtering still apply.'],
  ['bash', 'shell', 'Shell description is rendered for actual shell, platform, temporary directory, output limits and timeout; final permission and user.tools filtering apply.'],
];

// [inventory, id, title, file, first line, last line, activation, explanation]
// Undefined last line means the whole public source file. Code records show
// source code, never a fabricated expansion of dynamic templates.
export const records = [
  ['prompts', 'prompt-provider-routing', 'Provider prompt routing', src + 'session/system.ts', 28, 51,
    'SystemPrompt.provider selects by ordered model.api.id branches, then provider ID, then fallback; request preparation may replace it with agent.prompt.',
    'Selection is conditional source behavior. Model publisher names do not identify the observed serving provider.'],
  ['prompts', 'prompt-environment', 'Environment and project reference templates', src + 'session/system.ts', 69, 105,
    'SystemPrompt.environment runs during main conversation assembly; described project references are sorted and included only when present.',
    'Template values are runtime model ID, working directory, workspace root, repository state, platform and date. This record preserves the template without local expansion.'],
  ['prompts', 'prompt-skills-mcp', 'Skill catalog and MCP server instructions', src + 'session/system.ts', 107, 137,
    'Skill guidance is omitted when skill is disabled. MCP instructions are included when no tools are declared or at least one server tool is permitted.',
    'Dynamic content comes from available skills and connected MCP servers; it is absent from this public-source inventory.'],
  ['prompts', 'prompt-main-assembly', 'Main conversation context assembly', src + 'session/prompt.ts', 1255, 1288,
    'Main session loop runs experimental.chat.messages.transform, loads environment/instructions/MCP/skills, converts history and calls the session processor.',
    'Environment precedes instructions, then MCP instructions and skill guidance. Structured output adds a system instruction; a last-step assistant instruction may be added.'],
  ['prompts', 'prompt-structured-output', 'Structured output instruction', src + 'session/prompt.ts', 74, 82,
    'Latest user format is json_schema; main assembly advertises StructuredOutput, adds the system instruction and requires a tool call.',
    'These are inline source constants, not an observed formatted request.'],
  ['prompts', 'prompt-max-steps', 'Maximum step instruction', core + 'session/runner/max-steps.ts', 1, undefined,
    'Main session loop appends this as assistant content when the configured agent step limit is reached; core runner has a separate call site.',
    'The source instruction changes what the harness asks the model to do at its configured limit.'],
  ['prompts', 'prompt-reminder-routing', 'Plan and build reminder routing', src + 'session/reminders.ts', 1, undefined,
    'SessionReminders.apply has separate paths for the experimental plan flag, current agent, previous assistant agent and real plan-file existence.',
    'The upstream synthetic flag identifies harness-generated message parts. This extraction creates no sessions or example transcripts.'],
  ['prompts', 'prompt-core-runner', 'Core runner system context assembly', core + 'session/runner/llm.ts', 168, 226,
    'Separate core SessionRunner.runTurn source path; applies when that runner is invoked, not merely because the source exists.',
    'Uses agent system plus a system-context baseline and converted history. Its activation and parity with a particular installed CLI require separate runtime evidence.'],
  ['prompts', 'prompt-compaction-templates', 'Compaction summary and update instructions', core + 'session/compaction.ts', 16, 55,
    'Compaction buildPrompt chooses new-summary or prior-summary update instructions; caller or plugin may replace the constructed prompt.',
    'Preserves exact summary structure and update rules from inline public source constants.'],
  ['prompts', 'prompt-compaction-assembly', 'Compaction prompt assembly and override', src + 'session/compaction.ts', 358, 439,
    'SessionCompaction.process selects the compaction agent/model and relevant history; experimental.session.compacting may provide a prompt or extra context.',
    'The conversation is serialized with prior summaries and passed through buildPrompt unless replaced. This request has no tools and an empty extra system list, while the compaction agent prompt is still applied by request preparation.'],
  ['prompts', 'prompt-compaction-builder', 'Compaction builder source', core + 'session/compaction.ts', 160, 175,
    'buildPrompt is used by the compaction source paths; input carries real history and optional previous summary.',
    'Creates conversation/prior-summary tags and appends the conditional instructions. No assembled session prompt is fabricated by extraction.'],
  ['prompts', 'prompt-task-continuation', 'Command task continuation instruction', src + 'session/prompt.ts', 430, 449,
    'Task subtask handling has a command value; otherwise this path returns before adding the continuation message.',
    'Adds a harness-generated user instruction to summarize task output and continue.'],
  ['prompts', 'prompt-agent-mention', 'Explicit agent mention guidance', src + 'session/prompt.ts', 974, 990,
    'Resolving a user part of type agent; the task permission result can add a user-invocation hint.',
    'Appends guidance to call the task tool with the named subagent. The actual name comes from the real user part.'],
  ['prompts', 'prompt-core-agents', 'Core agent plugin prompts and permissions', core + 'plugin/agent.ts', 1, undefined,
    'Separate core agent plugin transforms the core agent catalog; this source path is distinct from legacy Agent.state.',
    'Contains build, explore, compaction, title and summary system text, plus built-in permissions. Source presence does not establish this plugin path was used in an installed CLI run.'],
  ['prompts', 'prompt-core-environment', 'Core environment and date context templates', core + 'system-context/builtins.ts', 1, undefined,
    'Core system-context built-ins register environment and date baseline/update loaders.',
    'The core runner consumes a context baseline; environment/date updates are separate templates from the legacy session environment.'],
  ['tools', 'tool-registry', 'Tool registration, model selection and definition hooks', src + 'tool/registry.ts', 120, 353,
    'ToolRegistry state combines built-ins, config-directory custom tools and plugin tools; model/flags/permissions affect advertised tools.',
    'tool.definition may alter descriptions or schemas. Task descriptions append permitted subagents; execute appends a visible MCP catalog.'],
  ['tools', 'tool-schema-lowering', 'Tool schema conversion and provider adaptation', src + 'session/tools.ts', 91, 134,
    'SessionTools.resolve materializes registry tools for the selected model before LLM request preparation.',
    'Schemas derive from ToolJsonSchema.fromTool then ProviderTransform.schema; descriptions and input schemas passed here may differ from raw source declarations.'],
  ['tools', 'tool-shell-rendering', 'Shell description rendering', src + 'tool/shell/prompt.ts', 1, undefined,
    'ShellPrompt.render selects bash, PowerShell or cmd guidance using actual shell and platform, then substitutes output limits, timeout and temporary directory.',
    'Includes the dynamic sections omitted by the short shell.txt template. No local shell description is fabricated.'],
  ['tools', 'tool-task-background', 'Task background guidance and schema selection', src + 'tool/task.ts', 25, 62,
    'experimentalBackgroundSubagents enables additional description and background parameter; initialization chooses BaseParameters when the flag is disabled.',
    'The registry also appends the current permitted subagent catalog.'],
  ['tools', 'tool-task-schema-selection', 'Task advertised schema switch', src + 'tool/task.ts', 360, 369,
    'TaskTool initializes using experimentalBackgroundSubagents.',
    'Parameters used internally and JSON Schema advertised to the model have different conditional paths.'],
  ['tools', 'tool-execute', 'MCP orchestration execute tool', src + 'tool/code-mode.ts', 12, 64,
    'experimentalCodeMode enabled and registry finds a visible nonempty MCP catalog; execute replaces directly advertised MCP tools.',
    'The confined orchestration script receives catalog instructions built from actual MCP tool descriptions and schemas.'],
  ['tools', 'tool-invalid', 'Invalid tool-call recovery', src + 'tool/invalid.ts', 1, undefined,
    'Registered built-in but excluded from activeTools; AI SDK repair path redirects unrecognized calls here.',
    'Source implementation includes its description and parameters; this does not establish that it was advertised or executed in a session.'],
  ['tools', 'tool-mcp-resources', 'MCP resource tools and schemas', src + 'session/tools.ts', 136, 386,
    'At least one connected MCP server advertises resource capability.',
    'Adds list_mcp_resources, list_mcp_resource_templates and read_mcp_resource with server/URI schemas. Runtime resources and bodies are private session evidence.'],
  ['tools', 'tool-mcp-direct', 'Direct MCP tool materialization', src + 'session/tools.ts', 388, 502,
    'experimentalCodeMode disabled; connected MCP tools are converted and provider schemas are adapted before request filtering.',
    'MCP server tool names, descriptions and schemas are runtime additions, not a fixed shipped tool list.'],
  ['tools', 'tool-structured-output', 'StructuredOutput description', src + 'session/prompt.ts', 74, 80,
    'Latest user format is json_schema; schema comes from that user request.',
    'A dynamic final-answer tool is added alongside the resolved tools.'],
  ['tools', 'tool-argument-errors', 'Tool validation feedback and output truncation', src + 'tool/tool.ts', 17, 34,
    'Tool wrapper rejects arguments that do not satisfy the advertised tool parameter decoder.',
    'InvalidArgumentsError produces model-facing rewrite guidance; tool outputs also have a truncation wrapper.'],
  ['tools', 'tool-skill-content', 'Skill tool loaded-content wrapper', src + 'tool/skill.ts', 21, 66,
    'User/model invokes the skill tool for an available skill and permission succeeds.',
    'Returns actual skill content with base-directory guidance and sampled files; these runtime values are not expanded into the source map.'],
  ['configuration', 'config-precedence', 'Configuration layers and overrides', src + 'config/config.ts', 328, 612,
    'Config.loadInstanceState merges enabled sources in source order; project/config-directory/organization/managed sources are conditional.',
    'Order: well-known remote config, global config, OPENCODE_CONFIG, project files, discovered config directories and Markdown agents, OPENCODE_CONFIG_CONTENT, active organization, managed directory, macOS managed preferences; later permission and legacy-tool compatibility transforms apply.'],
  ['configuration', 'config-global-merge', 'Global config files and instruction-array merge', src + 'config/config.ts', 40, 52,
    'Layer merges use mergeConfigConcatArrays during instance loading; global file loader has its own ordered merges.',
    'Instructions concatenate and deduplicate when both layers provide them. Other fields use deep merge; do not assume all arrays concatenate.'],
  ['configuration', 'config-global-files', 'Global config file order', src + 'config/config.ts', 260, 293,
    'Global config is loaded before project layers.',
    'Loads config.json, opencode.json, then opencode.jsonc in that order.'],
  ['configuration', 'config-paths', 'Project and config directory discovery', src + 'config/paths.ts', 1, undefined,
    'OPENCODE_DISABLE_PROJECT_CONFIG excludes project discovery; OPENCODE_CONFIG_DIR appends an explicit directory.',
    'Project file list is reversed before merge. Config directories include global config, discovered .opencode directories, home .opencode and the explicit config directory, deduplicated.'],
  ['configuration', 'config-variables', 'Environment and file substitutions', src + 'config/variable.ts', 1, undefined,
    'ConfigVariable.substitute expands {env:VAR} and {file:path} when config text is loaded.',
    'File references resolve relative to the config directory, with home expansion; full contents are escaped into JSON text. This extractor never expands private configuration.'],
  ['configuration', 'config-agent-markdown', 'Markdown agent configuration', src + 'config/agent.ts', 1, undefined,
    'Config directories are scanned for agent/agents Markdown and legacy mode/modes Markdown.',
    'Markdown body becomes the agent prompt; frontmatter fields configure it.'],
  ['configuration', 'config-agent-state', 'Built-in agents and configured agent overrides', src + 'agent/agent.ts', 119, 294,
    'Agent.state merges default and user permissions, built-in agents and cfg.agent entries.',
    'Configured agents can disable agents or override model, variant, prompt, description, temperature, top_p, mode, steps, options and permissions.'],
  ['configuration', 'config-agent-default', 'Default agent selection', src + 'agent/agent.ts', 329, 348,
    'Configured default_agent is used when valid, visible and not subagent-only; otherwise the first visible primary/all agent wins.',
    'Agent choice determines prompt replacement, permissions and options applied later.'],
  ['configuration', 'config-instructions', 'Global, project and configured instructions', src + 'session/instruction.ts', 58, 178,
    'Instruction.system loads discovered instructions; Claude compatibility may be disabled and project config may be disabled.',
    'First existing global candidate wins. Project search tries AGENTS.md, CLAUDE.md when enabled, then deprecated CONTEXT.md and stops at the first filename with matches. Explicit instructions add globs/files or fetched URL bodies.'],
  ['configuration', 'config-nearby-instructions', 'Instructions discovered while reading a file', src + 'session/instruction.ts', 179, 221,
    'Instruction.resolve walks upward from the read target, within the instance directory, and excludes system/already-loaded/already-claimed files.',
    'Nearby instruction contents attach once per assistant message and are not a universal system prompt layer.'],
  ['configuration', 'config-runtime-flags', 'Runtime feature flags', src + 'effect/runtime-flags.ts', 1, undefined,
    'RuntimeFlags service reads environment configuration; selected flags inherit OPENCODE_EXPERIMENTAL unless explicitly set.',
    'Includes native LLM, WebSockets, plan, code mode, LSP, question, references, external skills, Claude compatibility, client and output-limit controls.'],
  ['configuration', 'config-core-flags', 'Configuration and catalog environment controls', core + 'flag/flag.ts', 1, undefined,
    'Flag fields read process environment; selected controls are evaluated at access time.',
    'Includes config path/content/directory, project-config disablement, permission override, catalog path/URL/fetch disablement and auto-compaction/pruning controls. Source extraction preserves variable names without reading their runtime values.'],
  ['network-tracing', 'network-request-preparation', 'Request preparation and plugin transforms', src + 'session/llm/request.ts', 56, 146,
    'LLMRequestPrep.prepare runs before the selected runtime executes.',
    'agent.prompt replaces provider prompt; then input.system and user.system append. Plugins may transform system, params and headers. Options merge base, model, agent and selected user variant in that order. OpenAI OAuth puts system text into instructions instead of system messages; GitLab workflows have a separate systemPrompt path.'],
  ['network-tracing', 'network-session-headers', 'Session identity headers and overrides', src + 'session/llm/request.ts', 177, 208,
    'Prepared request headers go to the selected runtime; model headers then plugin headers can override earlier fields.',
    'x-opencode-session-id and optional x-opencode-parent-session-id provide explicit identity. Non-opencode providers also get x-session-affinity and X-Session-Id. Header presence in source does not prove the final captured request includes them.'],
  ['network-tracing', 'network-tool-filtering', 'Final request tool filtering', src + 'session/llm/request.ts', 152, 178,
    'After params/headers hooks, resolveTools applies agent/session permissions and per-user tools disablement; selected Responses-family tools have strict false.',
    'GitHub Copilot may gain a compatibility _noop tool only when no tools remain and replayed history contains tool calls.'],
  ['network-tracing', 'network-tool-permissions', 'Final permission and user-tools gate', src + 'session/llm/request.ts', 210, 216,
    'resolveTools is called during request preparation.',
    'Tool presence in the registry differs from final request inclusion.'],
  ['network-tracing', 'network-runtime-selection', 'Default AI SDK and opt-in native runtime', src + 'session/llm.ts', 224, 380,
    'experimentalNativeLlm attempts native runtime; unsupported status falls back to AI SDK. Otherwise streamText is the default path.',
    'Default path passes prepared headers/messages/tools/options and applies ProviderTransform.message through middleware before SDK serialization.'],
  ['network-tracing', 'network-native-runtime', 'Native runtime support gate', src + 'session/llm/native-runtime.ts', 48, 75,
    'Only when experimentalNativeLlm is enabled and this status gate succeeds.',
    'Accepts provider IDs openai, anthropic or starting opencode, with supported SDK packages and configured API key; OAuth additionally needs the OpenAI fetch override. OpenRouter/Alibaba/DeepSeek/Moonshot do not pass this provider-ID gate.'],
  ['network-tracing', 'network-native-request', 'Native request conversion and adapter selection', src + 'session/llm/native-request.ts', 1, undefined,
    'Native request adapter invoked only by a caller whose runtime support gate admits it; standalone package adapters are not proof of main CLI use.',
    'Converts system messages, text, media, reasoning, tools and provider metadata into canonical LLM requests; selects adapters by model.api.npm.'],
  ['network-tracing', 'network-provider-packages', 'Bundled provider SDK factories', src + 'provider/provider.ts', 144, 175,
    'Provider.resolveSDK selects factory using the configured or catalog-derived model.api.npm.',
    'Includes OpenRouter, Alibaba and OpenAI-compatible SDK factories. SDK dependency versions are pinned in packages/opencode/package.json, separately from installed CLI identity.'],
  ['network-tracing', 'network-openrouter-headers', 'OpenRouter attribution headers', src + 'provider/provider.ts', 513, 524,
    'OpenRouter custom provider loader is used and headers are not overridden downstream.',
    'Sets HTTP-Referer and X-Title for the client. These headers do not identify an upstream serving provider.'],
  ['network-tracing', 'network-model-definition', 'Model endpoint, capabilities and options', src + 'provider/provider.ts', 1542, 1631,
    'Config-defined model is merged with existing/catalog defaults.',
    'api.id, npm package and URL have separate precedence. Interleaved reasoning can be configured; a new OpenAI-compatible DeepSeek model defaults to reasoning_content. Model options and headers are merged, and configured variants can disable defaults.'],
  ['network-tracing', 'network-sdk-endpoint', 'Resolved SDK endpoint and fetch layer', src + 'provider/provider.ts', 1783, 1864,
    'resolveSDK loads the selected provider package.',
    'Nonempty provider.options.baseURL takes precedence over model.api.url, then configured/environment substitutions apply. Provider credentials and model headers are merged before the timeout-aware fetch wrapper. Actual captured host remains the evidence of client destination.'],
  ['network-tracing', 'network-model-catalog', 'Runtime model catalog source', core + 'models-dev.ts', 1, undefined,
    'ModelsDev loads cache/OPENCODE_MODELS_PATH, build-injected snapshot, or network fetch when enabled; periodic refresh is conditional.',
    'Catalog URL defaults to models.opencode.ai and can be overridden. Provider endpoints/capabilities from a live catalog are not frozen by this source pin and are not copied into this inventory.'],
  ['network-tracing', 'network-reasoning-replay', 'DeepSeek and interleaved reasoning replay', src + 'provider/transform.ts', 303, 351,
    'ProviderTransform normalization applies after preceding provider-specific branches; DeepSeek names receive empty reasoning placeholders when missing.',
    'Configured interleaved reasoning fields move assistant reasoning into OpenAI-compatible message options, excluding the OpenRouter SDK path. Empty placeholders are harness compatibility data, not evidence of model reasoning.'],
  ['network-tracing', 'network-reasoning-defaults', 'Provider reasoning and usage defaults', src + 'provider/transform.ts', 1220, 1415,
    'ProviderTransform.options or smallOptions creates defaults before model/agent/user variant merges.',
    'OpenRouter requests usage inclusion. Kimi Anthropic-compatible reasoning uses adaptive summarized thinking/high effort. Alibaba-cn OpenAI-compatible reasoning enables thinking except kimi-k2-thinking. Small-model options may disable reasoning. Source settings do not establish visible returned reasoning.'],
  ['network-tracing', 'network-reasoning-variants', 'Reasoning variant fallback branches', src + 'provider/transform.ts', 790, 879,
    'Reasoning capability enabled and no authoritative reasoning_options variants supersede these fallback branches.',
    'Kimi on Anthropic-compatible transports has adaptive thinking efforts. Earlier DeepSeek/Kimi/Qwen name branches return no generic variants. OpenRouter effort variants only apply if earlier branches did not return.'],
  ['network-tracing', 'network-catalog-reasoning', 'Catalog-defined reasoning controls', src + 'provider/transform.ts', 1717, undefined,
    'Model catalog provides reasoning_options; effort, toggle or token-budget variants are mapped to selected SDK settings.',
    'OpenRouter maps effort/budget to reasoning; Alibaba maps toggle/budget to enableThinking/thinkingBudget. This is configuration mapping, not provider response evidence.'],
  ['network-tracing', 'network-option-namespaces', 'Provider option namespaces', src + 'provider/transform.ts', 1421, 1483,
    'ProviderTransform.providerOptions is called before SDK execution.',
    'Maps package to expected namespace; Azure receives openai and azure; gateway options split routing controls from model publisher options. Provider IDs and model publishers are distinct.'],
  ['network-tracing', 'network-ai-sdk-reasoning', 'AI SDK stream normalization', src + 'session/llm/ai-sdk.ts', 1, undefined,
    'Default AI SDK runtime fullStream is converted into canonical LLMEvents.',
    'Reasoning start/delta/end remain separate from text; usage and finish metadata are normalized; errors fail the stream. This code does not reconstruct hidden/encrypted reasoning.'],
  ['network-tracing', 'network-reasoning-storage', 'Visible reasoning persistence', src + 'session/processor.ts', 278, 315,
    'Reasoning events arrive from the selected runtime with a preceding reasoning-start.',
    'Persists distinct reasoning parts and provider metadata. Orphan reasoning deltas are dropped, so stored exports can differ from raw wire streams.'],
  ['network-tracing', 'network-finish-usage', 'Step finish, usage and provider transformations', src + 'session/processor.ts', 435, 468,
    'Session processor receives step-finish from the selected runtime.',
    'Stores finish reason and normalized tokens/cost; logs provider-reported dropped thinking blocks and closes remaining reasoning parts. Raw capture is needed to inspect metadata that does not survive export.'],
  ['network-tracing', 'network-encrypted-reasoning', 'Opaque reasoning replay metadata', llm + 'protocols/openai-responses.ts', 283, 300,
    'Native OpenAI Responses lowering sees a reasoning part with valid provider item ID metadata.',
    'Visible part text becomes summary_text; reasoningEncryptedContent is passed separately as opaque encrypted_content or null. Encrypted bytes are not readable reasoning text.'],
  ['network-tracing', 'network-reasoning-summary-stream', 'Native reasoning summary deltas and opaque metadata', llm + 'protocols/openai-responses.ts', 624, 671,
    'Native OpenAI Responses stream receives reasoning summary and output-item events.',
    'Summary deltas become visible reasoning events, while encrypted_content stays in provider metadata. Ordering is handled on a best-effort basis when events are unexpected.'],
  ['network-tracing', 'network-history-replay', 'Stored assistant history replay and model changes', src + 'session/message-v2.ts', 249, 386,
    'MessageV2 converts stored session parts for a new selected provider/model.',
    'For the same model, reasoning parts preserve provider metadata. When model changes, nonempty reasoning becomes text and metadata is omitted. Completed, failed and interrupted tools have separate replay paths.'],
  ['network-tracing', 'network-export', 'Native JSON export boundary', src + 'cli/cmd/export.ts', 222, undefined,
    'User explicitly runs export for a real session; optional sanitize mode redacts transcript/file data.',
    'Writes {info,messages}, where each message carries info and parts from session storage. This is stored session evidence, not the fully assembled request or exact system prompt.'],
  ['network-tracing', 'network-openrouter-package', 'Native package OpenRouter protocol', llm + 'providers/openrouter.ts', 1, undefined,
    'Standalone native package OpenRouter route is selected; main CLI native runtime gate restricts provider IDs separately.',
    'Uses OpenAI Chat stream protocol at /chat/completions, adding usage/reasoning/prompt-cache body options. Default host comes from the native profile. It does not establish an observed serving provider or downstream hop.'],
  ['network-tracing', 'network-native-profiles', 'Native OpenAI-compatible endpoint profiles', llm + 'providers/openai-compatible-profile.ts', 1, undefined,
    'Native package provider helpers use their default profile unless baseURL is overridden.',
    'Includes openrouter.ai/api/v1 and api.deepseek.com/v1. Main CLI endpoint defaults may instead come from the dynamic catalog or config.'],
  ['network-tracing', 'network-chat-wire', 'Native Chat request and response fields', llm + 'protocols/openai-chat.ts', 34, 160,
    'Native OpenAI Chat-compatible protocol serializes a canonical request and decodes SSE events.',
    'Source schema separates system/user/assistant/tool content, tool function schemas, reasoning_content, usage.reasoning_tokens and finish_reason. This native schema is not proof of the default external SDK wire format.'],
  ['network-tracing', 'network-core-runner-headers', 'Core runner request identity and context', core + 'session/runner/llm.ts', 203, 226,
    'Separate core SessionRunner source path constructs a request.',
    'Adds exact session/parent headers, model request, agent system and context baseline. Live runtime evidence is needed to identify which path produced a capture.'],
];
